name: Deploy to AWS Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check AWS CLI version
      run: aws --version

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
        aws-region: ap-south-1

    - name: Zip Lambda files
      run: zip python.zip lambda_function.py hello.py

    - name: Upload to AWS Lambda
      run: |
        aws lambda update-function-code \
          --function-name myGithubLambda \
          --zip-file fileb://python.zip
